{
 "title": "Non-Kubernetes Etcd by Prometheus",
 "description": "Dashboard for etcd clusters NOT of Kubernetes",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Leader",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_is_leader{job!=\"kubernetes-etcd\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "The number of leader changes seen",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{job!=\"kubernetes-etcd\"})"
    }
   ]
  },
  {
   "title": "The total number of failed proposals seen",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_proposals_failed_total{job!=\"kubernetes-etcd\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job!=\"kubernetes-etcd\",grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{job!=\"kubernetes-etcd\",grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{job!=\"kubernetes-etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job!=\"kubernetes-etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{job!=\"kubernetes-etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job!=\"kubernetes-etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{job!=\"kubernetes-etcd\"}",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job!=\"kubernetes-etcd\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job!=\"kubernetes-etcd\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job!=\"kubernetes-etcd\"}",
     "legendFormat": "{{instance}} Resident Memory"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job!=\"kubernetes-etcd\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{job!=\"kubernetes-etcd\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{job!=\"kubernetes-etcd\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{job!=\"kubernetes-etcd\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Raft Proposal Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_failed_total{job!=\"kubernetes-etcd\"}[5m])",
     "legendFormat": "failed @ {{ instance }}"
    },
    {
     "expr": "rate(etcd_server_proposals_committed_total{job!=\"kubernetes-etcd\"}[5m])",
     "legendFormat": "committed @ {{ instance }}"
    },
    {
     "expr": "rate(etcd_server_proposals_applied_total{job!=\"kubernetes-etcd\"}[5m])",
     "legendFormat": "applied @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job!=\"kubernetes-etcd\"}[1d])",
     "legendFormat": "{{instance}} Total Leader Elections Per Day"
    }
   ]
  },
  {
   "title": "Raft Proposal Totals",
   "type": "graph",
   "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_proposals_committed_total{job!=\"kubernetes-etcd\"}",
     "legendFormat": "committed @ {{ instance }}"
    },
    {
     "expr": "etcd_server_proposals_applied_total{job!=\"kubernetes-etcd\"}",
     "legendFormat": "applied @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Proposals pending",
   "type": "graph",
   "description": "indicates how many proposals are queued to commit. Rising pending proposals suggests there is a high client load or the member cannot commit proposals.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_proposals_pending{job!=\"kubernetes-etcd\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".*etcd.*\",name!~\".*etcd-operator.*\"}[1m])) by (pod_name,container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ pod_name }} {{ container_label_io_kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=~\".*etcd.*\",name!~\".*etcd-operator.*\"}",
     "legendFormat": "Working set @ {{ instance }}"
    },
    {
     "expr": "container_memory_usage_bytes{name=~\".*etcd.*\",name!~\".*etcd-operator.*\"}",
     "legendFormat": "Usage @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job!=\"kubernetes-etcd\"}[1m])",
     "legendFormat": "Received (gRPC clients) @ {{ instance }}"
    },
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{job!=\"kubernetes-etcd\"}[1m])",
     "legendFormat": "Transmit (gRPC clients) @ {{ instance }}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".*etcd.*\",name!~\".*etcd-operator.*\"}[1m])) by (instance)",
     "legendFormat": "Receive (cAdvisor) @ {{ instance }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".*etcd.*\",name!~\".*etcd-operator.*\"}[1m])) by (instance)",
     "legendFormat": "Transmit (cAdvisor) @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Disks Utilizations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_disk_wal_fsync_duration_seconds_sum{job!=\"kubernetes-etcd\"}[1m])",
     "legendFormat": "WAL fsync @ {{ instance }}"
    },
    {
     "expr": "rate(etcd_disk_backend_commit_duration_seconds_sum{job!=\"kubernetes-etcd\"}[1m])",
     "legendFormat": "BE commit  @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Filesystem I/O Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{name=~\".*etcd.*\",name!~\".*etcd-operator.*\"}[1m])",
     "legendFormat": "Writes @ {{ instance }}"
    },
    {
     "expr": "rate(container_fs_reads_bytes_total{name=~\".*etcd.*\",name!~\".*etcd-operator.*\"}[1m])",
     "legendFormat": "Reads @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Utilization by Snapshot Saves",
   "type": "graph",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_debugging_snap_save_total_duration_seconds_sum{job!=\"kubernetes-etcd\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}