{
 "title": "KOS Externals",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "99th Percentile Subnet Create-to-Validated Latency secs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_subnet_create_to_validated_latency_seconds_bucket{statusErr=\"ok\"}[1m]))",
     "legendFormat": "99%ile valid subnets "
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_subnet_create_to_validated_latency_seconds_bucket{statusErr=\"err\"}[1m]))",
     "legendFormat": "99%ile conflicting subnets"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kos_subnet_validator_subnet_create_to_validated_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "99%ile total"
    }
   ]
  },
  {
   "title": "Address Controller Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_attachment_create_to_address_latency_seconds_bucket[1m]))",
     "legendFormat": "99%ile address"
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_attachment_create_to_lock_latency_seconds_bucket[1m]))",
     "legendFormat": "99%ile lock"
    }
   ]
  },
  {
   "title": "99th Percentile Create-To-Local-Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_create_to_local_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "99th Percentile Attachment Create-to-Ready Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_create_to_status_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "99th Percentile of Ping Test Duration (secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_exec_duration_secs_bucket{what=\"postCreateExec\"}[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Average Ping Test Duration (secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_attachment_exec_duration_secs_sum{what=\"postCreateExec\"}[1m])/rate(kos_agent_attachment_exec_duration_secs_count{what=\"postCreateExec\"}[1m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Ping Tests/sec, by Exit Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_attachment_exec_status_count{what=\"postCreateExec\"}[1m])",
     "legendFormat": "{{ node }} {{ exitStatus }}"
    }
   ]
  }
 ]
}