/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	network "k8s.io/examples/staging/kos/pkg/apis/network"
)

// FakeNetworkAttachments implements NetworkAttachmentInterface
type FakeNetworkAttachments struct {
	Fake *FakeNetwork
	ns   string
}

var networkattachmentsResource = schema.GroupVersionResource{Group: "network.example.com", Version: "", Resource: "networkattachments"}

var networkattachmentsKind = schema.GroupVersionKind{Group: "network.example.com", Version: "", Kind: "NetworkAttachment"}

// Get takes name of the networkAttachment, and returns the corresponding networkAttachment object, and an error if there is any.
func (c *FakeNetworkAttachments) Get(name string, options v1.GetOptions) (result *network.NetworkAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(networkattachmentsResource, c.ns, name), &network.NetworkAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*network.NetworkAttachment), err
}

// List takes label and field selectors, and returns the list of NetworkAttachments that match those selectors.
func (c *FakeNetworkAttachments) List(opts v1.ListOptions) (result *network.NetworkAttachmentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(networkattachmentsResource, networkattachmentsKind, c.ns, opts), &network.NetworkAttachmentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &network.NetworkAttachmentList{ListMeta: obj.(*network.NetworkAttachmentList).ListMeta}
	for _, item := range obj.(*network.NetworkAttachmentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkAttachments.
func (c *FakeNetworkAttachments) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(networkattachmentsResource, c.ns, opts))

}

// Create takes the representation of a networkAttachment and creates it.  Returns the server's representation of the networkAttachment, and an error, if there is any.
func (c *FakeNetworkAttachments) Create(networkAttachment *network.NetworkAttachment) (result *network.NetworkAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(networkattachmentsResource, c.ns, networkAttachment), &network.NetworkAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*network.NetworkAttachment), err
}

// Update takes the representation of a networkAttachment and updates it. Returns the server's representation of the networkAttachment, and an error, if there is any.
func (c *FakeNetworkAttachments) Update(networkAttachment *network.NetworkAttachment) (result *network.NetworkAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(networkattachmentsResource, c.ns, networkAttachment), &network.NetworkAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*network.NetworkAttachment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkAttachments) UpdateStatus(networkAttachment *network.NetworkAttachment) (*network.NetworkAttachment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(networkattachmentsResource, "status", c.ns, networkAttachment), &network.NetworkAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*network.NetworkAttachment), err
}

// Delete takes name of the networkAttachment and deletes it. Returns an error if one occurs.
func (c *FakeNetworkAttachments) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(networkattachmentsResource, c.ns, name), &network.NetworkAttachment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkAttachments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(networkattachmentsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &network.NetworkAttachmentList{})
	return err
}

// Patch applies the patch and returns the patched networkAttachment.
func (c *FakeNetworkAttachments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *network.NetworkAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkattachmentsResource, c.ns, name, pt, data, subresources...), &network.NetworkAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*network.NetworkAttachment), err
}
