apiVersion: v2
name: ai-starter-kit
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"


dependencies:
  - name: kuberay-operator
    condition: ray-cluster.enabled
    version: "1.3.0"
    repository: "https://ray-project.github.io/kuberay-helm"
  - name: ray-cluster
    condition: ray-cluster.enabled
    version: "1.3.0"
    repository: "https://ray-project.github.io/kuberay-helm"
  - name: jupyterhub
    version: "4.2.0"
    repository: "https://hub.jupyter.org/helm-chart/"
  - name: mlflow
    version: "0.12.0"
    repository: "https://community-charts.github.io/helm-charts"
  - name: ollama
    condition: ollama.enabled
    version: "1.27.0"
    repository: "https://helm.otwld.com"
