ray-cluster:
  enabled: false

ramalama:
  enabled: true
  command:
    - /bin/sh
    - -c
    - ramalama pull qwen2.5:1.5b && ramalama serve qwen2.5:1.5b --port 8080
  image:
    repository: "quay.io/ramalama/ramalama"
    tag: "latest"
    pullPolicy: IfNotPresent
