jupyterhub:
  nameOverride: "jupyterhub"
  postgresql:
    nameOverride: "jupyterhub-postgresql"
    enabled: true
    auth:
      password: "changeme"

  singleuser:
    image:
      tag: "5.0.0-debian-12-r2"
    fsGid: 100
    defaultUrl: "/lab/tree/welcome.ipynb"
    lifecycleHooks:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "pip install -r /tmp/requirements.txt"]
    initContainers:
      - name: model-initializer
        image: python:3.9-slim-bullseye
        env:
          - name: TRANSFORMERS_CACHE
            value: /tmp/models-cache
          - name: HF_HOME
            value: /tmp/models-cache
        command:
          - /bin/sh
          - -c
          - |
            set -e
            pip install --no-cache-dir -r /tmp/requirements.txt
            python /tmp/download_models.py
        volumeMounts:
          - name: requirements-txt
            mountPath: /tmp/requirements.txt
            subPath: requirements.txt
            readOnly: true
          - name: models-cache
            mountPath: /tmp/models-cache
          - name: hf-download-script
            mountPath: /tmp/download_models.py
            subPath: download_models.py
            readOnly: true
          - name: hf-token-secret
            mountPath: "/etc/secrets/huggingface"
            readOnly: true
    extraVolumes:
      - name: requirements-txt
        configMap:
          name: "{{ .Release.Name }}-requirements-txt"
      - name: models-cache
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-models-cache-pvc"
      - name: hf-download-script
        configMap:
          name: "{{ .Release.Name }}-hf-download-script"
      - name: welcome-notebook
        configMap:
          name: "{{ .Release.Name }}-welcome-notebook"
      - name: ray-notebook
        configMap:
          name: "{{ .Release.Name }}-ray-notebook"
      - name: hf-token-secret
        secret:
          secretName: "{{ .Release.Name }}-hf-token-secret"
          optional: true
    extraVolumeMounts:
      - name: requirements-txt
        mountPath: /tmp/requirements.txt
        subPath: requirements.txt
      - name: models-cache
        mountPath: /tmp/models-cache
      - name: hf-download-script
        mountPath: /tmp/download_models.py
        subPath: download_models.py
      - name: welcome-notebook
        mountPath: /tmp/welcome.ipynb
        subPath: welcome.ipynb
      - name: ray-notebook
        mountPath: /tmp/ray.ipynb
        subPath: ray.ipynb
      - name: hf-token-secret
        mountPath: "/etc/secrets/huggingface"
        readOnly: true
    extraEnvVars:
        RAY_ADDRESS: "ray://{{ .Release.Name }}-kuberay-head-svc:10001"
        MLFLOW_TRACKING_URI: "http://{{ .Release.Name }}-mlflow:5000"
        # JUPYTERLAB_DIR: "/opt"
    resources:
      limits:
        memory: 16Gi
      requests:
        memory: 4Gi
  hub:
    password: "sneakypass"
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    # extraEnvVars:
    #     - name: "RAY_ADDRESS"
    #       value: "{{ .Release.Name }}-kuberay-head-svc"
    #     - name: "MLFLOW_TRACKING_URI"
    #       value: "http://{{ .Release.Name }}-mlflow-tracking"

ray-cluster:
  image:
    tag: "2.41.0-py311-cpu-aarch64"
  head:
    serviceType: ClusterIP
    resources:
      requests:
        cpu: "1"
        memory: "2G"
      limits:
        cpu: "4"
        memory: "8G"
  worker:
    resources:
      requests:
        cpu: "1"
        memory: "2G"
      limits:
        cpu: "4"
        memory: "8G"

mlflow:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

huggingface:
  # Provide your Hugging Face token here to download gated or private models.
  # It is recommended to set this via --set or a separate values file, e.g.,
  # --set huggingface.token=hf_...
  token: ""

modelsCachePvc:
  enabled: true
  # To use the default StorageClass, set storageClassName to null or omit it.
  # To use a specific StorageClass (e.g. "standard-rwo" on GKE), provide its name.
  # To create a PVC that doesn't request any StorageClass, set it to an empty string ("").
  storageClassName: null
  accessModes:
    - ReadWriteOnce
  size: 10Gi

localPersistence:
  # For local development with minikube, this allows persisting the models-cache
  # on the host machine, surviving `minikube stop/start`.
  # 1. Create a directory on your host: `mkdir -p /data/models-cache`
  # 2. Start minikube with the mount: `minikube start --mount --mount-string="/data/models-cache:/data/models-cache"`
  # 3. Set enabled to true below, or via `--set localPersistence.enabled=true`
  enabled: true
  # This path must match the destination path inside the minikube node.
  hostPath: "/tmp/models-cache"
