// +build !ignore_autogenerated

/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	network "k8s.io/examples/staging/kos/pkg/apis/network"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ExecReport)(nil), (*network.ExecReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExecReport_To_network_ExecReport(a.(*ExecReport), b.(*network.ExecReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.ExecReport)(nil), (*ExecReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_ExecReport_To_v1alpha1_ExecReport(a.(*network.ExecReport), b.(*ExecReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPLock)(nil), (*network.IPLock)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPLock_To_network_IPLock(a.(*IPLock), b.(*network.IPLock), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.IPLock)(nil), (*IPLock)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_IPLock_To_v1alpha1_IPLock(a.(*network.IPLock), b.(*IPLock), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPLockList)(nil), (*network.IPLockList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPLockList_To_network_IPLockList(a.(*IPLockList), b.(*network.IPLockList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.IPLockList)(nil), (*IPLockList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_IPLockList_To_v1alpha1_IPLockList(a.(*network.IPLockList), b.(*IPLockList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPLockSpec)(nil), (*network.IPLockSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPLockSpec_To_network_IPLockSpec(a.(*IPLockSpec), b.(*network.IPLockSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.IPLockSpec)(nil), (*IPLockSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_IPLockSpec_To_v1alpha1_IPLockSpec(a.(*network.IPLockSpec), b.(*IPLockSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkAttachment)(nil), (*network.NetworkAttachment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkAttachment_To_network_NetworkAttachment(a.(*NetworkAttachment), b.(*network.NetworkAttachment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.NetworkAttachment)(nil), (*NetworkAttachment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_NetworkAttachment_To_v1alpha1_NetworkAttachment(a.(*network.NetworkAttachment), b.(*NetworkAttachment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkAttachmentErrors)(nil), (*network.NetworkAttachmentErrors)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkAttachmentErrors_To_network_NetworkAttachmentErrors(a.(*NetworkAttachmentErrors), b.(*network.NetworkAttachmentErrors), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.NetworkAttachmentErrors)(nil), (*NetworkAttachmentErrors)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_NetworkAttachmentErrors_To_v1alpha1_NetworkAttachmentErrors(a.(*network.NetworkAttachmentErrors), b.(*NetworkAttachmentErrors), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkAttachmentList)(nil), (*network.NetworkAttachmentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkAttachmentList_To_network_NetworkAttachmentList(a.(*NetworkAttachmentList), b.(*network.NetworkAttachmentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.NetworkAttachmentList)(nil), (*NetworkAttachmentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_NetworkAttachmentList_To_v1alpha1_NetworkAttachmentList(a.(*network.NetworkAttachmentList), b.(*NetworkAttachmentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkAttachmentSpec)(nil), (*network.NetworkAttachmentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkAttachmentSpec_To_network_NetworkAttachmentSpec(a.(*NetworkAttachmentSpec), b.(*network.NetworkAttachmentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.NetworkAttachmentSpec)(nil), (*NetworkAttachmentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_NetworkAttachmentSpec_To_v1alpha1_NetworkAttachmentSpec(a.(*network.NetworkAttachmentSpec), b.(*NetworkAttachmentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkAttachmentStatus)(nil), (*network.NetworkAttachmentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkAttachmentStatus_To_network_NetworkAttachmentStatus(a.(*NetworkAttachmentStatus), b.(*network.NetworkAttachmentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.NetworkAttachmentStatus)(nil), (*NetworkAttachmentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_NetworkAttachmentStatus_To_v1alpha1_NetworkAttachmentStatus(a.(*network.NetworkAttachmentStatus), b.(*NetworkAttachmentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Subnet)(nil), (*network.Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Subnet_To_network_Subnet(a.(*Subnet), b.(*network.Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.Subnet)(nil), (*Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_Subnet_To_v1alpha1_Subnet(a.(*network.Subnet), b.(*Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubnetCondition)(nil), (*network.SubnetCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SubnetCondition_To_network_SubnetCondition(a.(*SubnetCondition), b.(*network.SubnetCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.SubnetCondition)(nil), (*SubnetCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_SubnetCondition_To_v1alpha1_SubnetCondition(a.(*network.SubnetCondition), b.(*SubnetCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubnetList)(nil), (*network.SubnetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SubnetList_To_network_SubnetList(a.(*SubnetList), b.(*network.SubnetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.SubnetList)(nil), (*SubnetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_SubnetList_To_v1alpha1_SubnetList(a.(*network.SubnetList), b.(*SubnetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubnetSpec)(nil), (*network.SubnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SubnetSpec_To_network_SubnetSpec(a.(*SubnetSpec), b.(*network.SubnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.SubnetSpec)(nil), (*SubnetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_SubnetSpec_To_v1alpha1_SubnetSpec(a.(*network.SubnetSpec), b.(*SubnetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubnetStatus)(nil), (*network.SubnetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SubnetStatus_To_network_SubnetStatus(a.(*SubnetStatus), b.(*network.SubnetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*network.SubnetStatus)(nil), (*SubnetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_network_SubnetStatus_To_v1alpha1_SubnetStatus(a.(*network.SubnetStatus), b.(*SubnetStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ExecReport_To_network_ExecReport(in *ExecReport, out *network.ExecReport, s conversion.Scope) error {
	out.ExitStatus = in.ExitStatus
	out.StartTime = in.StartTime
	out.StopTime = in.StopTime
	out.StdOut = in.StdOut
	out.StdErr = in.StdErr
	return nil
}

// Convert_v1alpha1_ExecReport_To_network_ExecReport is an autogenerated conversion function.
func Convert_v1alpha1_ExecReport_To_network_ExecReport(in *ExecReport, out *network.ExecReport, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExecReport_To_network_ExecReport(in, out, s)
}

func autoConvert_network_ExecReport_To_v1alpha1_ExecReport(in *network.ExecReport, out *ExecReport, s conversion.Scope) error {
	out.ExitStatus = in.ExitStatus
	out.StartTime = in.StartTime
	out.StopTime = in.StopTime
	out.StdOut = in.StdOut
	out.StdErr = in.StdErr
	return nil
}

// Convert_network_ExecReport_To_v1alpha1_ExecReport is an autogenerated conversion function.
func Convert_network_ExecReport_To_v1alpha1_ExecReport(in *network.ExecReport, out *ExecReport, s conversion.Scope) error {
	return autoConvert_network_ExecReport_To_v1alpha1_ExecReport(in, out, s)
}

func autoConvert_v1alpha1_IPLock_To_network_IPLock(in *IPLock, out *network.IPLock, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_IPLockSpec_To_network_IPLockSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_IPLock_To_network_IPLock is an autogenerated conversion function.
func Convert_v1alpha1_IPLock_To_network_IPLock(in *IPLock, out *network.IPLock, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPLock_To_network_IPLock(in, out, s)
}

func autoConvert_network_IPLock_To_v1alpha1_IPLock(in *network.IPLock, out *IPLock, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_network_IPLockSpec_To_v1alpha1_IPLockSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_network_IPLock_To_v1alpha1_IPLock is an autogenerated conversion function.
func Convert_network_IPLock_To_v1alpha1_IPLock(in *network.IPLock, out *IPLock, s conversion.Scope) error {
	return autoConvert_network_IPLock_To_v1alpha1_IPLock(in, out, s)
}

func autoConvert_v1alpha1_IPLockList_To_network_IPLockList(in *IPLockList, out *network.IPLockList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]network.IPLock)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_IPLockList_To_network_IPLockList is an autogenerated conversion function.
func Convert_v1alpha1_IPLockList_To_network_IPLockList(in *IPLockList, out *network.IPLockList, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPLockList_To_network_IPLockList(in, out, s)
}

func autoConvert_network_IPLockList_To_v1alpha1_IPLockList(in *network.IPLockList, out *IPLockList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]IPLock)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_network_IPLockList_To_v1alpha1_IPLockList is an autogenerated conversion function.
func Convert_network_IPLockList_To_v1alpha1_IPLockList(in *network.IPLockList, out *IPLockList, s conversion.Scope) error {
	return autoConvert_network_IPLockList_To_v1alpha1_IPLockList(in, out, s)
}

func autoConvert_v1alpha1_IPLockSpec_To_network_IPLockSpec(in *IPLockSpec, out *network.IPLockSpec, s conversion.Scope) error {
	out.SubnetName = in.SubnetName
	return nil
}

// Convert_v1alpha1_IPLockSpec_To_network_IPLockSpec is an autogenerated conversion function.
func Convert_v1alpha1_IPLockSpec_To_network_IPLockSpec(in *IPLockSpec, out *network.IPLockSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPLockSpec_To_network_IPLockSpec(in, out, s)
}

func autoConvert_network_IPLockSpec_To_v1alpha1_IPLockSpec(in *network.IPLockSpec, out *IPLockSpec, s conversion.Scope) error {
	out.SubnetName = in.SubnetName
	return nil
}

// Convert_network_IPLockSpec_To_v1alpha1_IPLockSpec is an autogenerated conversion function.
func Convert_network_IPLockSpec_To_v1alpha1_IPLockSpec(in *network.IPLockSpec, out *IPLockSpec, s conversion.Scope) error {
	return autoConvert_network_IPLockSpec_To_v1alpha1_IPLockSpec(in, out, s)
}

func autoConvert_v1alpha1_NetworkAttachment_To_network_NetworkAttachment(in *NetworkAttachment, out *network.NetworkAttachment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_NetworkAttachmentSpec_To_network_NetworkAttachmentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_NetworkAttachmentStatus_To_network_NetworkAttachmentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_NetworkAttachment_To_network_NetworkAttachment is an autogenerated conversion function.
func Convert_v1alpha1_NetworkAttachment_To_network_NetworkAttachment(in *NetworkAttachment, out *network.NetworkAttachment, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkAttachment_To_network_NetworkAttachment(in, out, s)
}

func autoConvert_network_NetworkAttachment_To_v1alpha1_NetworkAttachment(in *network.NetworkAttachment, out *NetworkAttachment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_network_NetworkAttachmentSpec_To_v1alpha1_NetworkAttachmentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_network_NetworkAttachmentStatus_To_v1alpha1_NetworkAttachmentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_network_NetworkAttachment_To_v1alpha1_NetworkAttachment is an autogenerated conversion function.
func Convert_network_NetworkAttachment_To_v1alpha1_NetworkAttachment(in *network.NetworkAttachment, out *NetworkAttachment, s conversion.Scope) error {
	return autoConvert_network_NetworkAttachment_To_v1alpha1_NetworkAttachment(in, out, s)
}

func autoConvert_v1alpha1_NetworkAttachmentErrors_To_network_NetworkAttachmentErrors(in *NetworkAttachmentErrors, out *network.NetworkAttachmentErrors, s conversion.Scope) error {
	out.IPAM = *(*[]string)(unsafe.Pointer(&in.IPAM))
	out.Host = *(*[]string)(unsafe.Pointer(&in.Host))
	return nil
}

// Convert_v1alpha1_NetworkAttachmentErrors_To_network_NetworkAttachmentErrors is an autogenerated conversion function.
func Convert_v1alpha1_NetworkAttachmentErrors_To_network_NetworkAttachmentErrors(in *NetworkAttachmentErrors, out *network.NetworkAttachmentErrors, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkAttachmentErrors_To_network_NetworkAttachmentErrors(in, out, s)
}

func autoConvert_network_NetworkAttachmentErrors_To_v1alpha1_NetworkAttachmentErrors(in *network.NetworkAttachmentErrors, out *NetworkAttachmentErrors, s conversion.Scope) error {
	out.IPAM = *(*[]string)(unsafe.Pointer(&in.IPAM))
	out.Host = *(*[]string)(unsafe.Pointer(&in.Host))
	return nil
}

// Convert_network_NetworkAttachmentErrors_To_v1alpha1_NetworkAttachmentErrors is an autogenerated conversion function.
func Convert_network_NetworkAttachmentErrors_To_v1alpha1_NetworkAttachmentErrors(in *network.NetworkAttachmentErrors, out *NetworkAttachmentErrors, s conversion.Scope) error {
	return autoConvert_network_NetworkAttachmentErrors_To_v1alpha1_NetworkAttachmentErrors(in, out, s)
}

func autoConvert_v1alpha1_NetworkAttachmentList_To_network_NetworkAttachmentList(in *NetworkAttachmentList, out *network.NetworkAttachmentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]network.NetworkAttachment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_NetworkAttachmentList_To_network_NetworkAttachmentList is an autogenerated conversion function.
func Convert_v1alpha1_NetworkAttachmentList_To_network_NetworkAttachmentList(in *NetworkAttachmentList, out *network.NetworkAttachmentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkAttachmentList_To_network_NetworkAttachmentList(in, out, s)
}

func autoConvert_network_NetworkAttachmentList_To_v1alpha1_NetworkAttachmentList(in *network.NetworkAttachmentList, out *NetworkAttachmentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NetworkAttachment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_network_NetworkAttachmentList_To_v1alpha1_NetworkAttachmentList is an autogenerated conversion function.
func Convert_network_NetworkAttachmentList_To_v1alpha1_NetworkAttachmentList(in *network.NetworkAttachmentList, out *NetworkAttachmentList, s conversion.Scope) error {
	return autoConvert_network_NetworkAttachmentList_To_v1alpha1_NetworkAttachmentList(in, out, s)
}

func autoConvert_v1alpha1_NetworkAttachmentSpec_To_network_NetworkAttachmentSpec(in *NetworkAttachmentSpec, out *network.NetworkAttachmentSpec, s conversion.Scope) error {
	out.Node = in.Node
	out.Subnet = in.Subnet
	out.PostCreateExec = *(*[]string)(unsafe.Pointer(&in.PostCreateExec))
	out.PostDeleteExec = *(*[]string)(unsafe.Pointer(&in.PostDeleteExec))
	return nil
}

// Convert_v1alpha1_NetworkAttachmentSpec_To_network_NetworkAttachmentSpec is an autogenerated conversion function.
func Convert_v1alpha1_NetworkAttachmentSpec_To_network_NetworkAttachmentSpec(in *NetworkAttachmentSpec, out *network.NetworkAttachmentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkAttachmentSpec_To_network_NetworkAttachmentSpec(in, out, s)
}

func autoConvert_network_NetworkAttachmentSpec_To_v1alpha1_NetworkAttachmentSpec(in *network.NetworkAttachmentSpec, out *NetworkAttachmentSpec, s conversion.Scope) error {
	out.Node = in.Node
	out.Subnet = in.Subnet
	out.PostCreateExec = *(*[]string)(unsafe.Pointer(&in.PostCreateExec))
	out.PostDeleteExec = *(*[]string)(unsafe.Pointer(&in.PostDeleteExec))
	return nil
}

// Convert_network_NetworkAttachmentSpec_To_v1alpha1_NetworkAttachmentSpec is an autogenerated conversion function.
func Convert_network_NetworkAttachmentSpec_To_v1alpha1_NetworkAttachmentSpec(in *network.NetworkAttachmentSpec, out *NetworkAttachmentSpec, s conversion.Scope) error {
	return autoConvert_network_NetworkAttachmentSpec_To_v1alpha1_NetworkAttachmentSpec(in, out, s)
}

func autoConvert_v1alpha1_NetworkAttachmentStatus_To_network_NetworkAttachmentStatus(in *NetworkAttachmentStatus, out *network.NetworkAttachmentStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_NetworkAttachmentErrors_To_network_NetworkAttachmentErrors(&in.Errors, &out.Errors, s); err != nil {
		return err
	}
	out.LockUID = in.LockUID
	out.AddressVNI = in.AddressVNI
	out.IPv4 = in.IPv4
	out.MACAddress = in.MACAddress
	out.IfcName = in.IfcName
	out.HostIP = in.HostIP
	out.PostCreateExecReport = (*network.ExecReport)(unsafe.Pointer(in.PostCreateExecReport))
	return nil
}

// Convert_v1alpha1_NetworkAttachmentStatus_To_network_NetworkAttachmentStatus is an autogenerated conversion function.
func Convert_v1alpha1_NetworkAttachmentStatus_To_network_NetworkAttachmentStatus(in *NetworkAttachmentStatus, out *network.NetworkAttachmentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkAttachmentStatus_To_network_NetworkAttachmentStatus(in, out, s)
}

func autoConvert_network_NetworkAttachmentStatus_To_v1alpha1_NetworkAttachmentStatus(in *network.NetworkAttachmentStatus, out *NetworkAttachmentStatus, s conversion.Scope) error {
	if err := Convert_network_NetworkAttachmentErrors_To_v1alpha1_NetworkAttachmentErrors(&in.Errors, &out.Errors, s); err != nil {
		return err
	}
	out.LockUID = in.LockUID
	out.AddressVNI = in.AddressVNI
	out.IPv4 = in.IPv4
	out.MACAddress = in.MACAddress
	out.IfcName = in.IfcName
	out.HostIP = in.HostIP
	out.PostCreateExecReport = (*ExecReport)(unsafe.Pointer(in.PostCreateExecReport))
	return nil
}

// Convert_network_NetworkAttachmentStatus_To_v1alpha1_NetworkAttachmentStatus is an autogenerated conversion function.
func Convert_network_NetworkAttachmentStatus_To_v1alpha1_NetworkAttachmentStatus(in *network.NetworkAttachmentStatus, out *NetworkAttachmentStatus, s conversion.Scope) error {
	return autoConvert_network_NetworkAttachmentStatus_To_v1alpha1_NetworkAttachmentStatus(in, out, s)
}

func autoConvert_v1alpha1_Subnet_To_network_Subnet(in *Subnet, out *network.Subnet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SubnetSpec_To_network_SubnetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SubnetStatus_To_network_SubnetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Subnet_To_network_Subnet is an autogenerated conversion function.
func Convert_v1alpha1_Subnet_To_network_Subnet(in *Subnet, out *network.Subnet, s conversion.Scope) error {
	return autoConvert_v1alpha1_Subnet_To_network_Subnet(in, out, s)
}

func autoConvert_network_Subnet_To_v1alpha1_Subnet(in *network.Subnet, out *Subnet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_network_SubnetSpec_To_v1alpha1_SubnetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_network_SubnetStatus_To_v1alpha1_SubnetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_network_Subnet_To_v1alpha1_Subnet is an autogenerated conversion function.
func Convert_network_Subnet_To_v1alpha1_Subnet(in *network.Subnet, out *Subnet, s conversion.Scope) error {
	return autoConvert_network_Subnet_To_v1alpha1_Subnet(in, out, s)
}

func autoConvert_v1alpha1_SubnetCondition_To_network_SubnetCondition(in *SubnetCondition, out *network.SubnetCondition, s conversion.Scope) error {
	out.Type = network.SubnetConditionType(in.Type)
	out.Status = network.ConditionStatus(in.Status)
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_SubnetCondition_To_network_SubnetCondition is an autogenerated conversion function.
func Convert_v1alpha1_SubnetCondition_To_network_SubnetCondition(in *SubnetCondition, out *network.SubnetCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubnetCondition_To_network_SubnetCondition(in, out, s)
}

func autoConvert_network_SubnetCondition_To_v1alpha1_SubnetCondition(in *network.SubnetCondition, out *SubnetCondition, s conversion.Scope) error {
	out.Type = SubnetConditionType(in.Type)
	out.Status = ConditionStatus(in.Status)
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_network_SubnetCondition_To_v1alpha1_SubnetCondition is an autogenerated conversion function.
func Convert_network_SubnetCondition_To_v1alpha1_SubnetCondition(in *network.SubnetCondition, out *SubnetCondition, s conversion.Scope) error {
	return autoConvert_network_SubnetCondition_To_v1alpha1_SubnetCondition(in, out, s)
}

func autoConvert_v1alpha1_SubnetList_To_network_SubnetList(in *SubnetList, out *network.SubnetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]network.Subnet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_SubnetList_To_network_SubnetList is an autogenerated conversion function.
func Convert_v1alpha1_SubnetList_To_network_SubnetList(in *SubnetList, out *network.SubnetList, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubnetList_To_network_SubnetList(in, out, s)
}

func autoConvert_network_SubnetList_To_v1alpha1_SubnetList(in *network.SubnetList, out *SubnetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Subnet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_network_SubnetList_To_v1alpha1_SubnetList is an autogenerated conversion function.
func Convert_network_SubnetList_To_v1alpha1_SubnetList(in *network.SubnetList, out *SubnetList, s conversion.Scope) error {
	return autoConvert_network_SubnetList_To_v1alpha1_SubnetList(in, out, s)
}

func autoConvert_v1alpha1_SubnetSpec_To_network_SubnetSpec(in *SubnetSpec, out *network.SubnetSpec, s conversion.Scope) error {
	out.IPv4 = in.IPv4
	out.VNI = in.VNI
	return nil
}

// Convert_v1alpha1_SubnetSpec_To_network_SubnetSpec is an autogenerated conversion function.
func Convert_v1alpha1_SubnetSpec_To_network_SubnetSpec(in *SubnetSpec, out *network.SubnetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubnetSpec_To_network_SubnetSpec(in, out, s)
}

func autoConvert_network_SubnetSpec_To_v1alpha1_SubnetSpec(in *network.SubnetSpec, out *SubnetSpec, s conversion.Scope) error {
	out.IPv4 = in.IPv4
	out.VNI = in.VNI
	return nil
}

// Convert_network_SubnetSpec_To_v1alpha1_SubnetSpec is an autogenerated conversion function.
func Convert_network_SubnetSpec_To_v1alpha1_SubnetSpec(in *network.SubnetSpec, out *SubnetSpec, s conversion.Scope) error {
	return autoConvert_network_SubnetSpec_To_v1alpha1_SubnetSpec(in, out, s)
}

func autoConvert_v1alpha1_SubnetStatus_To_network_SubnetStatus(in *SubnetStatus, out *network.SubnetStatus, s conversion.Scope) error {
	out.Usable = in.Usable
	out.Conditions = *(*[]network.SubnetCondition)(unsafe.Pointer(&in.Conditions))
	out.Errors = *(*[]string)(unsafe.Pointer(&in.Errors))
	return nil
}

// Convert_v1alpha1_SubnetStatus_To_network_SubnetStatus is an autogenerated conversion function.
func Convert_v1alpha1_SubnetStatus_To_network_SubnetStatus(in *SubnetStatus, out *network.SubnetStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubnetStatus_To_network_SubnetStatus(in, out, s)
}

func autoConvert_network_SubnetStatus_To_v1alpha1_SubnetStatus(in *network.SubnetStatus, out *SubnetStatus, s conversion.Scope) error {
	out.Usable = in.Usable
	out.Conditions = *(*[]SubnetCondition)(unsafe.Pointer(&in.Conditions))
	out.Errors = *(*[]string)(unsafe.Pointer(&in.Errors))
	return nil
}

// Convert_network_SubnetStatus_To_v1alpha1_SubnetStatus is an autogenerated conversion function.
func Convert_network_SubnetStatus_To_v1alpha1_SubnetStatus(in *network.SubnetStatus, out *SubnetStatus, s conversion.Scope) error {
	return autoConvert_network_SubnetStatus_To_v1alpha1_SubnetStatus(in, out, s)
}
