---
{{- /*
Create ConfigMaps for jupyterhub singleuser pods.
These ConfigMaps are mounted as volumes.
*/ -}}
{{- range $path, $_ := .Files.Glob "files/*" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" $.Release.Name (base $path | replace "." "-" | replace "_" "-") }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
data:
  {{ base $path | quote }}: |-
{{ $.Files.Get $path | nindent 4 }}
{{- end }}
