{{- if .Values.huggingface.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hf-token-secret
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
stringData:
  token: {{ .Values.huggingface.token }}
{{- end }}