{{- if .Values.ramalama.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-starter-kit.fullname" . }}-ramalama
  labels:
    {{- include "ai-starter-kit.labels" . | nindent 4 }}
    app.kubernetes.io/component: ramalama
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ai-starter-kit.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ramalama
  template:
    metadata:
      labels:
        {{- include "ai-starter-kit.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ramalama
    spec:
      {{- if .Values.ramalama.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.ramalama.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: ramalama
        image: "{{ .Values.ramalama.image.repository }}:{{ .Values.ramalama.image.tag }}"
        imagePullPolicy: {{ .Values.ramalama.image.pullPolicy }}
        {{- if .Values.ramalama.command }}
        command:
          {{- toYaml .Values.ramalama.command | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 8080
          protocol: TCP
        {{- if .Values.ramalama.resources }}
        resources:
          {{- toYaml .Values.ramalama.resources | nindent 10 }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-starter-kit.fullname" . }}-ramalama
  labels:
    {{- include "ai-starter-kit.labels" . | nindent 4 }}
    app.kubernetes.io/component: ramalama
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "ai-starter-kit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ramalama
{{- end }}