kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sio-small
provisioner: kubernetes.io/scaleio
parameters:
  gateway: https://localhost:443/api 
  system: scaleio
  protectionDomain: pd01
  storagePool: pd01
  secretRef: sio-secret
  fsType: xfs
