apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-model-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/models/my_model
